# Generated by Django 6.0.6 on 2026-08-04 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=12)),
                ('nombre', models.CharField(help_text='Ej. "3°A" o "Sala 2"', max_length=20)),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], default='MANANA', max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nivel', 'nombre', 'turno'],
                'constraints': [models.UniqueConstraint(fields=('nivel', 'nombre', 'turno'), name='uniq_seccion_nivel_nombre_turno')],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'El DNI debe tener 7 u 8 dígitos.')])),
                ('domicilio', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='alumnos.seccion')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
