# Generated by Django 6.0.6 on 2026-08-07 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_vinculo_alumno_familiares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('secciones', models.ManyToManyField(blank=True, related_name='grupos', to='alumnos.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='AlcanceAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=12)),
                ('turno', models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10, null=True)),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('autoridad', 'nivel', 'turno'), name='uniq_alcance_autoridad_nivel_turno')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='alumnos.seccion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('docente', 'seccion'), name='uniq_asignacion_docente_seccion')],
            },
        ),
        migrations.CreateModel(
            name='AlcanceGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcances_grupo', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcances', to='institucion.grupopersonalizado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('autoridad', 'grupo'), name='uniq_alcance_grupo')],
            },
        ),
    ]
