# Generated by Django 6.0.6 on 2026-08-05 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_vinculo_alumno_familiares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('tipo_destino', models.CharField(choices=[('INDIVIDUAL', 'Un alumno'), ('SECCION', 'Una seccion')], default='SECCION', max_length=10)),
                ('requiere_acuse', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_individuales', to='alumnos.alumno')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_emitidos', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='alumnos.seccion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EntregaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado_en', models.DateTimeField(auto_now_add=True)),
                ('acusado_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='alumnos.alumno')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='comunicados.comunicado')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entregado_en'],
                'constraints': [models.UniqueConstraint(fields=('comunicado', 'familiar', 'alumno'), name='uniq_entrega_comunicado_familiar_alumno')],
            },
        ),
    ]
