# Generated by Django 6.0.6 on 2026-08-07 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='categoria',
            field=models.CharField(choices=[('ACADEMICO', 'Academico'), ('ARANCELARIO', 'Arancelario')], default='ACADEMICO', max_length=12),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='institucion.grupopersonalizado'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='nivel',
            field=models.CharField(blank=True, choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='turno',
            field=models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='tipo_destino',
            field=models.CharField(choices=[('INDIVIDUAL', 'Un alumno'), ('SECCION', 'Una seccion'), ('TURNO', 'Un nivel-turno'), ('NIVEL', 'Un nivel completo'), ('GRUPO', 'Un grupo personalizado'), ('ESCUELA', 'Toda la escuela')], default='SECCION', max_length=10),
        ),
    ]
