# Generated by Django 6.0.6 on 2026-08-04 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director/a'), ('VICEDIRECTOR', 'Vicedirector/a'), ('PRECEPTOR', 'Preceptor/a'), ('TESORERO', 'Tesorero/a')], help_text='Solo para autoridades. Define qué categoría de comunicado puede emitir.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, help_text='7 u 8 dígitos, sin puntos ni espacios.', max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'El DNI debe tener 7 u 8 dígitos, sin puntos.')]),
        ),
    ]
